apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme"
spec:
  selector:
    matchLabels:
      app: "acme"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "acme"
    spec:
      containers:
      - image: {{ .Values.image }}
        name: "acme"
        env:
          - name: DB_HOSTNAME
            value: {{ .Values.dbhost }}
          - name: DB_USERNAME
            value: {{ .Values.dbuser }}
          - name: DB_PASSWORD
            value: {{ .Values.dbpassword }}
          - name: DB_NAME
            value: {{ .Values.dbname }}
        ports:
        - containerPort: 3000
